WINDOW_WIDTH = 800
WINDOW_HEIGHT = 500

BLACK_COLOR = (0, 0, 0)
WHITE_COLOR = (255, 255, 255)

BACKGROUP_PATH = 'photos/background.JPG'




BIRD_PATH = 'photos/bird.JPG'
BIRD_WIDTH = 30
BIRD_HEIGHT = 30
BIRD_START_POS_X = 170
BIRD_START_POS_Y = 320
BIRD_SPEED_X = 4

ACCELERATION_SIZE = 0.3
JUMP_SPEED = -7

START_TEXT = 'Press space to play!'
START_TEXT_FONT = 'Ariel'
START_TEXT_SIZE = 30
START_TEXT_POS_X = 70
START_TEXT_POS_Y = 50

END_TEXT = 'Better luck next time!'
END_TEXT_FONT = 'Ariel'
END_TEXT_SIZE = 30
END_TEXT_POS_X = 70
END_TEXT_POS_Y = 50

SCORE_TEXT = 'SCORE: '
SCORE_TEXT_FONT = 'Ariel'
SCORE_TEXT_SIZE = 30
SCORE_TEXT_POS_X = 120
SCORE_TEXT_POS_Y = 90

SPIKE_PATH = 'photos/spike.JPG'
SPIKE_WIDTH = 40
SPIKE_HEIGHT = 10
SPIKES_NUM = 3

SCORE_ADDITION = SPIKES_NUM

BEST_SCORE_FILE_PATH = 'files/best_score.txt'
BEST_SCORE_TEXT = 'BEST SCORE: '
BEST_SCORE_TEXT_FONT = 'Ariel'
BEST_SCORE_TEXT_SIZE = 20
BEST_SCORE_TEXT_POS_X = 120
BEST_SCORE_TEXT_POS_Y = 600

BONUS_PATH = 'photos/bonus.JPG'
BONUS_WIDTH = 20
BONUS_HEIGHT = 20
BONUS_ADDITION = 10
