WINDOW_WIDTH = 800
WINDOW_HEIGHT = 500

BLACK_COLOR = (0, 0, 0)
WHITE_COLOR = (255, 255, 255)
GREEN_COLOR = (0, 255, 0)
RED_COLOR = (255, 0, 0)

BACKGROUND_PATH = 'photos/background.JPG'

QUESTION_FONT = 'Ariel'
QUESTION_SIZE = 50
QUESTION_POS_X = 20
QUESTION_POS_Y = 70

ANSWER_FONT = 'Ariel'
ANSWER_SIZE = 50
ANSWER_RECT_WIDTH = 50
ANSWER_RECT_HEIGHT = 30
ANSWER_INDEXED_POS = [(100, 200), (400, 200), (100, 300), (400, 300)]

QUESTIONS_FILE_PATH = 'files/questions.txt'
ANSWERS_FILE_PATH = 'files/answers.txt'

START_BUTTON_TEXT = 'Click here to start!'
START_BUTTON_TEXT_FONT = 'Ariel'
START_BUTTON_TEXT_SIZE = 30
START_BUTTON_POS_X = 300
START_BUTTON_POS_Y = 300
START_BUTTON_WIDTH = 180
START_BUTTON_HEIGHT = 20

WELCOME_MSG = "Welcome! let's see how smart you are..."
WELCOME_MSG_POS_X = 60
WELCOME_MSG_POS_Y = 30
WELCOME_MSG_FONT = 'Ariel'
WELCOME_MSG_SIZE = 50

TIME_FOR_QUESTION = 4
TIMER_PATH = 'photos/timer.PNG'
TIMER_POS_X = 600
TIMER_POS_Y = 230
TIMER_WIDTH = 80
TIMER_HEIGHT = 80

TIME_POS_X = TIMER_POS_X + 20
TIME_POS_Y = TIMER_POS_Y - 20
TIME_FONT = 'Ariel'
TIME_SIZE = 30

SCORE_TEXT = 'SCORE: '
SCORE_TEXT_SIZE = 40
SCORE_TEXT_FONT = 'Ariel'
SCORE_POS_X = WINDOW_WIDTH / 2 - 65
SCORE_POS_Y = WINDOW_HEIGHT - 40

END_TEXT = 'Well done! Nice score!'
END_TEXT_FONT = 'Ariel'
END_TEXT_SIZE = 80
END_TEXT_POS_X = WINDOW_WIDTH / 2 - 300
END_TEXT_POS_Y = WINDOW_HEIGHT / 2 - 100
